package com.project.bankaws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-06T03:02:46.318+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.project.com/BankaWS", name = "BankaPort")
@XmlSeeAlso({com.project.zaglavlje_preseka.ObjectFactory.class, com.project.common_types.ObjectFactory.class, com.project.nalog_za_placanje.ObjectFactory.class, com.project.stavka_preseka.ObjectFactory.class, com.project.mt900.ObjectFactory.class, com.project.zahtev_za_izvod.ObjectFactory.class, com.project.mt102.ObjectFactory.class, com.project.mt103.ObjectFactory.class, com.project.mt910.ObjectFactory.class, com.project.presek.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)
public interface BankaPort {

    @WebResult(name = "status", targetNamespace = "http://www.project.com/common_types", partName = "statusResponse")
    @WebMethod
    public com.project.common_types.Status odradiClearing() throws ClearingFault;

    @WebResult(name = "status", targetNamespace = "http://www.project.com/common_types", partName = "statusResponse")
    @WebMethod
    public com.project.common_types.Status receiveMT910(
        @WebParam(partName = "MT910", name = "mt910", targetNamespace = "http://www.project.com/mt910")
        com.project.mt910.Mt910 mt910
    ) throws ReceiveMT103Fault;

    @WebResult(name = "status", targetNamespace = "http://www.project.com/common_types", partName = "statusResponse")
    @WebMethod
    public com.project.common_types.Status receiveMT102(
        @WebParam(partName = "MT102", name = "mt102", targetNamespace = "http://www.project.com/mt102")
        com.project.mt102.Mt102 mt102
    ) throws ReceiveMT102Fault;

    @WebResult(name = "Presek", targetNamespace = "http://www.project.com/presek", partName = "Presek")
    @WebMethod
    public com.project.presek.Presek sendPresek(
        @WebParam(partName = "Zahtev", name = "Zahtev_za_Izvod", targetNamespace = "http://www.project.com/zahtev_za_izvod")
        com.project.zahtev_za_izvod.ZahtevZaIzvod zahtev
    ) throws SendPresekFault;

    @WebResult(name = "status", targetNamespace = "http://www.project.com/common_types", partName = "statusResponse")
    @WebMethod
    public com.project.common_types.Status receiveMT103(
        @WebParam(partName = "MT103", name = "mt103", targetNamespace = "http://www.project.com/mt103")
        com.project.mt103.Mt103 mt103
    ) throws ReceiveMT103Fault;

    @WebResult(name = "status", targetNamespace = "http://www.project.com/common_types", partName = "statusResponse")
    @WebMethod
    public com.project.common_types.Status receiveNalog(
        @WebParam(partName = "Nalog", name = "Nalog_Za_Placanje", targetNamespace = "http://www.project.com/nalog_za_placanje")
        com.project.nalog_za_placanje.NalogZaPlacanje nalog
    ) throws ReceiveNalogFault;
}
