
package com.project.bankaws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-06T03:02:46.286+02:00
 * Generated source version: 2.6.5
 */

@WebFault(name = "status", targetNamespace = "http://www.project.com/common_types")
public class SendPresekFault extends Exception {
    
    private com.project.common_types.Status status;

    public SendPresekFault() {
        super();
    }
    
    public SendPresekFault(String message) {
        super(message);
    }
    
    public SendPresekFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SendPresekFault(String message, com.project.common_types.Status status) {
        super(message);
        this.status = status;
    }

    public SendPresekFault(String message, com.project.common_types.Status status, Throwable cause) {
        super(message, cause);
        this.status = status;
    }

    public com.project.common_types.Status getFaultInfo() {
        return this.status;
    }
}
