package com.project.banka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.project.cbws.ReceiveMT102Fault;
import com.project.cbws.ReceiveMT103Fault;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-07T02:41:04.837+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.project.com/BankaWS", name = "BankaPort")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)
public interface BankaPort {

    @WebResult(name = "status", targetNamespace = "http://www.project.com/common_types", partName = "statusResponse")
    @WebMethod
    public com.project.common_types.Status odradiClearing() throws ClearingFault;

    @WebResult(name = "status", targetNamespace = "http://www.project.com/common_types", partName = "statusResponse")
    @WebMethod
    public com.project.common_types.Status receiveMT910(
        @WebParam(partName = "MT910", name = "mt910", targetNamespace = "http://www.project.com/mt910")
        com.project.mt910.Mt910 mt910
    ) throws ReceiveMT103Fault;

    @WebResult(name = "status", targetNamespace = "http://www.project.com/common_types", partName = "statusResponse")
    @WebMethod
    public com.project.common_types.Status receiveMT102(
        @WebParam(partName = "MT102", name = "mt102", targetNamespace = "http://www.project.com/mt102")
        com.project.mt102.Mt102 mt102
    ) throws ReceiveMT102Fault;

   
    @WebResult(name = "status", targetNamespace = "http://www.project.com/common_types", partName = "statusResponse")
    @WebMethod
    public com.project.common_types.Status receiveMT103(
        @WebParam(partName = "MT103", name = "mt103", targetNamespace = "http://www.project.com/mt103")
        com.project.mt103.Mt103 mt103
    ) throws ReceiveMT103Fault;

   
}
