
package com.project.banka;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-07T02:41:04.783+02:00
 * Generated source version: 2.6.5
 */

@WebFault(name = "status", targetNamespace = "http://www.project.com/common_types")
public class ClearingFault extends Exception {
    
    private com.project.common_types.Status status;

    public ClearingFault() {
        super();
    }
    
    public ClearingFault(String message) {
        super(message);
    }
    
    public ClearingFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ClearingFault(String message, com.project.common_types.Status status) {
        super(message);
        this.status = status;
    }

    public ClearingFault(String message, com.project.common_types.Status status, Throwable cause) {
        super(message, cause);
        this.status = status;
    }

    public com.project.common_types.Status getFaultInfo() {
        return this.status;
    }
}
