package com.project.cbws;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-26T20:07:50.506+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.project.com/CBws", name = "BankaPort")
@XmlSeeAlso({com.project.common_types.ObjectFactory.class, com.project.mt900.ObjectFactory.class, com.project.mt102.ObjectFactory.class, com.project.mt103.ObjectFactory.class, com.project.mt910.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)
public interface BankaPort {

    @WebResult(name = "mt103", targetNamespace = "http://www.project.com/mt103", partName = "MT103")
    @WebMethod
    public com.project.mt103.Mt103 sendMT103(
        @WebParam(partName = "MT900RTGS", name = "mt900RTGS", targetNamespace = "http://www.project.com/mt900")
        com.project.mt900.Mt900RTGS mt900RTGS
    ) throws SendMT103Fault;

    @Oneway
    @WebMethod
    public void receiveMT102(
        @WebParam(partName = "MT102", name = "mt102", targetNamespace = "http://www.project.com/mt102")
        com.project.mt102.Mt102 mt102
    );

    @Oneway
    @WebMethod
    public void receiveMT103(
        @WebParam(partName = "MT103", name = "mt103", targetNamespace = "http://www.project.com/mt103")
        com.project.mt103.Mt103 mt103
    );

    @WebResult(name = "mt102", targetNamespace = "http://www.project.com/mt102", partName = "MT102")
    @WebMethod
    public com.project.mt102.Mt102 sendMT102(
        @WebParam(partName = "MT900Clearing", name = "mt900Clearing", targetNamespace = "http://www.project.com/mt900")
        com.project.mt900.Mt900Clearing mt900Clearing
    ) throws SendMT102Fault;

    @Oneway
    @WebMethod
    public void receiveMT910(
        @WebParam(partName = "MT910", name = "mt910", targetNamespace = "http://www.project.com/mt910")
        com.project.mt910.Mt910 mt910
    );
}
