
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.project.cbws;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-26T20:07:50.490+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "BankaService",
                      portName = "BankaPort",
                      targetNamespace = "http://www.project.com/CBws",
                      wsdlLocation = "file:/C:/Users/Geek/Desktop/Wp/XMLProject/WEB-INF/wsdl/Banka.wsdl",
                      endpointInterface = "com.project.cbws.BankaPort")
                      
public class BankaPortImpl implements BankaPort {

    private static final Logger LOG = Logger.getLogger(BankaPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.project.cbws.BankaPort#sendMT103(com.project.mt900.Mt900RTGS  mt900RTGS )*
     */
    public com.project.mt103.Mt103 sendMT103(com.project.mt900.Mt900RTGS mt900RTGS) throws SendMT103Fault    { 
        LOG.info("Executing operation sendMT103");
        System.out.println(mt900RTGS);
        try {
            com.project.mt103.Mt103 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SendMT103Fault("sendMT103fault...");
    }

    /* (non-Javadoc)
     * @see com.project.cbws.BankaPort#receiveMT102(com.project.mt102.Mt102  mt102 )*
     */
    public void receiveMT102(com.project.mt102.Mt102 mt102) { 
        LOG.info("Executing operation receiveMT102");
        System.out.println(mt102);
        try {
        //	checkMT102();
        	
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.project.cbws.BankaPort#receiveMT103(com.project.mt103.Mt103  mt103 )*
     */
    public void receiveMT103(com.project.mt103.Mt103 mt103) { 
        LOG.info("Executing operation receiveMT103");
        System.out.println(mt103);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.project.cbws.BankaPort#sendMT102(com.project.mt900.Mt900Clearing  mt900Clearing )*
     */
    public com.project.mt102.Mt102 sendMT102(com.project.mt900.Mt900Clearing mt900Clearing) throws SendMT102Fault    { 
        LOG.info("Executing operation sendMT102");
        System.out.println(mt900Clearing);
        try {
            com.project.mt102.Mt102 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SendMT102Fault("sendMT102fault...");
    }

    /* (non-Javadoc)
     * @see com.project.cbws.BankaPort#receiveMT910(com.project.mt910.Mt910  mt910 )*
     */
    public void receiveMT910(com.project.mt910.Mt910 mt910) { 
        LOG.info("Executing operation receiveMT910");
        System.out.println(mt910);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
