package com.project.cbws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-26T20:07:46.007+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "CBservice", 
                  wsdlLocation = "file:/C:/Users/Geek/Desktop/Wp/XMLProject/WEB-INF/wsdl/CB.wsdl",
                  targetNamespace = "http://www.project.com/CBws") 
public class CBservice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.project.com/CBws", "CBservice");
    public final static QName CBport = new QName("http://www.project.com/CBws", "CBport");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Geek/Desktop/Wp/XMLProject/WEB-INF/wsdl/CB.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CBservice.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Geek/Desktop/Wp/XMLProject/WEB-INF/wsdl/CB.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CBservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CBservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CBservice() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CBservice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CBservice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CBservice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CBport
     */
    @WebEndpoint(name = "CBport")
    public CBport getCBport() {
        return super.getPort(CBport, CBport.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CBport
     */
    @WebEndpoint(name = "CBport")
    public CBport getCBport(WebServiceFeature... features) {
        return super.getPort(CBport, CBport.class, features);
    }

}
