//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.14 at 02:30:13 PM CEST 
//


package com.project.racuni;

import javax.xml.bind.annotation.XmlRegistry;

import com.project.common_types.Status;
import com.project.common_types.TBanka;
import com.project.common_types.TBankarskiRacunKlijenta;
import com.project.common_types.TRacunKlijenta;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.project.banka package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.project.banka
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Racuni }
     * 
     */
    public Racuni createRacuni() {
        return new Racuni();
    }

    /**
     * Create an instance of {@link TBankarskiRacunKlijenta }
     * 
     */
    public TBankarskiRacunKlijenta createTBankarskiRacunKlijenta() {
        return new TBankarskiRacunKlijenta();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link TBanka }
     * 
     */
    public TBanka createTBanka() {
        return new TBanka();
    }

    /**
     * Create an instance of {@link TRacunKlijenta }
     * 
     */
    public TRacunKlijenta createTRacunKlijenta() {
        return new TRacunKlijenta();
    }

}
