
package com.project.cbws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-08T18:33:59.895+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class CBport_CBport_Client {

    private static final QName SERVICE_NAME = new QName("http://www.project.com/CBws", "CBservice");

    private CBport_CBport_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CBservice.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CBservice ss = new CBservice(wsdlURL, SERVICE_NAME);
        CBport port = ss.getCBport();  
        
        {
        System.out.println("Invoking receiveMT102CB...");
        com.project.mt102.Mt102 _receiveMT102CB_mt102 = new com.project.mt102.Mt102();
        try {
            com.project.mt900.Mt900Clearing _receiveMT102CB__return = port.receiveMT102CB(_receiveMT102CB_mt102);
            System.out.println("receiveMT102CB.result=" + _receiveMT102CB__return);

        } catch (ReceiveMT102Fault e) { 
            System.out.println("Expected exception: receiveMT102fault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking receiveMT103CB...");
        com.project.mt103.Mt103 _receiveMT103CB_mt103 = new com.project.mt103.Mt103();
        try {
            com.project.mt900.Mt900RTGS _receiveMT103CB__return = port.receiveMT103CB(_receiveMT103CB_mt103);
            System.out.println("receiveMT103CB.result=" + _receiveMT103CB__return);

        } catch (ReceiveMT103Fault e) { 
            System.out.println("Expected exception: receiveMT103fault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
