package com.project.cbws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-08T18:34:00.021+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.project.com/CBws", name = "CBport")
@XmlSeeAlso({com.project.common_types.ObjectFactory.class, com.project.nalog_za_placanje.ObjectFactory.class, com.project.mt900.ObjectFactory.class, com.project.mt102.ObjectFactory.class, com.project.mt103.ObjectFactory.class, com.project.mt910.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CBport {

    @WebResult(name = "mt900Clearing", targetNamespace = "http://www.project.com/mt900", partName = "MT900Clearing")
    @WebMethod
    public com.project.mt900.Mt900Clearing receiveMT102CB(
        @WebParam(partName = "MT102", name = "mt102", targetNamespace = "http://www.project.com/mt102")
        com.project.mt102.Mt102 mt102
    ) throws ReceiveMT102Fault;

    @WebResult(name = "mt900RTGS", targetNamespace = "http://www.project.com/mt900", partName = "MT900RTGS")
    @WebMethod
    public com.project.mt900.Mt900RTGS receiveMT103CB(
        @WebParam(partName = "MT103", name = "mt103", targetNamespace = "http://www.project.com/mt103")
        com.project.mt103.Mt103 mt103
    ) throws ReceiveMT103Fault;
}
