package yu.ac.ns.ftn.informatika.ws.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-26T11:11:30.734+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://informatika.ftn.ns.ac.yu/ws/hello", name = "RTGSDocument")
@XmlSeeAlso({yu.ac.ns.ftn.informatika.ws.hello.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RTGSDocument {

    @WebResult(name = "ResponseRTGS", targetNamespace = "http://informatika.ftn.ns.ac.yu/ws/hello/types", partName = "ResponseRTGS")
    @WebMethod
    public yu.ac.ns.ftn.informatika.ws.hello.types.ResponseRTGS requestRTGS(
        @WebParam(partName = "RequestRTGS", name = "RequestRTGS", targetNamespace = "http://informatika.ftn.ns.ac.yu/ws/hello/types")
        yu.ac.ns.ftn.informatika.ws.hello.types.RTGSnalog requestRTGS
    );
}
