//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 02:46:20 PM CEST 
//


package com.project.transakcije;

import javax.xml.bind.annotation.XmlRegistry;

import com.project.common_types.Status;
import com.project.common_types.TBanka;
import com.project.common_types.TBankarskiRacunKlijenta;
import com.project.common_types.TRacunKlijenta;
import com.project.nalog_za_placanje.NalogZaPlacanje;
import com.project.nalog_za_placanje.Placanje;
import com.project.nalog_za_placanje.Uplata;
import com.project.stavka_preseka.StavkaPreseka;
import com.project.stavka_preseka.Transakcija;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.project.transakcije package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.project.transakcije
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Transakcije }
     * 
     */
    public Transakcije createTransakcije() {
        return new Transakcije();
    }

    /**
     * Create an instance of {@link Transakcija }
     * 
     */
    public Transakcija createTransakcija() {
        return new Transakcija();
    }

    /**
     * Create an instance of {@link StavkaPreseka }
     * 
     */
    public StavkaPreseka createStavkaPreseka() {
        return new StavkaPreseka();
    }

    /**
     * Create an instance of {@link Uplata }
     * 
     */
    public Uplata createUplata() {
        return new Uplata();
    }

    /**
     * Create an instance of {@link TRacunKlijenta }
     * 
     */
    public TRacunKlijenta createTRacunKlijenta() {
        return new TRacunKlijenta();
    }

    /**
     * Create an instance of {@link TBankarskiRacunKlijenta }
     * 
     */
    public TBankarskiRacunKlijenta createTBankarskiRacunKlijenta() {
        return new TBankarskiRacunKlijenta();
    }

    /**
     * Create an instance of {@link NalogZaPlacanje }
     * 
     */
    public NalogZaPlacanje createNalogZaPlacanje() {
        return new NalogZaPlacanje();
    }

    /**
     * Create an instance of {@link Placanje }
     * 
     */
    public Placanje createPlacanje() {
        return new Placanje();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link TBanka }
     * 
     */
    public TBanka createTBanka() {
        return new TBanka();
    }

}
