//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 08:20:13 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.project.com/security", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.project.security;
